"""Vocabulario canonico de reject_codes do ESAA — fonte unica de verdade.

Todos os codigos emitidos via ESAAError em src/esaa/*.py devem estar
declarados aqui. O teste tests/test_reject_codes_inventory.py garante isso.

Organizacao em 3 familias:
- WORKFLOW_GATE_CODES: aplicados pelo state machine / workflow gates (WG-001..005).
- OPERATIONAL_CODES: erros de runtime (store, lock, schema, init, snapshot, etc.).
- HOTFIX_CODES: validacao especifica de hotfix.create (FIX-1811).

Cada codigo e exposto como constante (str) para uso preferencial em
`raise ESAAError(STORE_LOCK_TIMEOUT, ...)`. Strings literais continuam
funcionando — mas o inventory test sinaliza se algum nao estiver registrado.
"""

from __future__ import annotations

# =============================================================================
# Workflow gates (WG-001..WG-005) — derivados do state machine.
# =============================================================================
MISSING_CLAIM = "MISSING_CLAIM"
MISSING_COMPLETE = "MISSING_COMPLETE"
MISSING_VERIFICATION = "MISSING_VERIFICATION"
WORKFLOW_GATE_VIOLATION = "WORKFLOW_GATE_VIOLATION"
ACTION_COLLAPSE = "ACTION_COLLAPSE"
PRIOR_STATUS_MISMATCH = "PRIOR_STATUS_MISMATCH"
LOCK_VIOLATION = "LOCK_VIOLATION"
IMMUTABLE_DONE_VIOLATION = "IMMUTABLE_DONE_VIOLATION"
REVIEW_ROLE_VIOLATION = "REVIEW_ROLE_VIOLATION"  # FIX-1807

WORKFLOW_GATE_CODES = frozenset(
    {
        MISSING_CLAIM,
        MISSING_COMPLETE,
        MISSING_VERIFICATION,
        WORKFLOW_GATE_VIOLATION,
        ACTION_COLLAPSE,
        PRIOR_STATUS_MISMATCH,
        LOCK_VIOLATION,
        IMMUTABLE_DONE_VIOLATION,
        REVIEW_ROLE_VIOLATION,
    }
)


# =============================================================================
# Operacional / runtime — erros do harness, store, schemas, snapshots, etc.
# =============================================================================
ADAPTER_EXECUTE_FAILED = "ADAPTER_EXECUTE_FAILED"
BOUNDARY_VIOLATION = "BOUNDARY_VIOLATION"
EDIT_AMBIGUOUS = "EDIT_AMBIGUOUS"
EDIT_BASE_MISMATCH = "EDIT_BASE_MISMATCH"
EDIT_INVALID = "EDIT_INVALID"
EDIT_TARGET_NOT_FOUND = "EDIT_TARGET_NOT_FOUND"
EXTERNAL_ROOT_NOT_ALLOWED = "EXTERNAL_ROOT_NOT_ALLOWED"
FILE_UPDATE_DUPLICATE_PATH = "FILE_UPDATE_DUPLICATE_PATH"  # ISS-T2042-DUP-FILE-UPDATES
RESOURCE_LIMIT_EXCEEDED = "RESOURCE_LIMIT_EXCEEDED"
BOOTSTRAP_PROFILE_INVALID = "BOOTSTRAP_PROFILE_INVALID"
BOOTSTRAP_TARGET_EXISTS = "BOOTSTRAP_TARGET_EXISTS"
CLEAR_REQUIRES_FORCE = "CLEAR_REQUIRES_FORCE"
DUPLICATE_TASK = "DUPLICATE_TASK"
EVENT_SEQ_NON_MONOTONIC = "EVENT_SEQ_NON_MONOTONIC"
INIT_BLOCKED = "INIT_BLOCKED"
INPUT_INVALID = "INPUT_INVALID"
INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
INVALID_ARGUMENT = "INVALID_ARGUMENT"
ISSUE_NOT_FOUND = "ISSUE_NOT_FOUND"
MAX_ATTEMPTS_EXCEEDED = "MAX_ATTEMPTS_EXCEEDED"
PLUGIN_FORBIDDEN_FILE = "PLUGIN_FORBIDDEN_FILE"
PLUGIN_INPUT_INVALID = "PLUGIN_INPUT_INVALID"
PLUGIN_INVALID_ID = "PLUGIN_INVALID_ID"
PLUGIN_INVALID_JSON = "PLUGIN_INVALID_JSON"
PLUGIN_LOCK_INVALID = "PLUGIN_LOCK_INVALID"
PLUGIN_NOT_A_DIRECTORY = "PLUGIN_NOT_A_DIRECTORY"
PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
PLUGIN_NOT_INSTALLED = "PLUGIN_NOT_INSTALLED"
PLUGIN_PATH_INVALID = "PLUGIN_PATH_INVALID"
PLUGIN_ROADMAP_INVALID = "PLUGIN_ROADMAP_INVALID"
PLUGIN_SCHEMA_INVALID = "PLUGIN_SCHEMA_INVALID"
PLUGIN_TARGET_EXISTS = "PLUGIN_TARGET_EXISTS"
ROADMAP_LOCK_INVALID = "ROADMAP_LOCK_INVALID"
ROADMAP_DIR_MISSING = "ROADMAP_DIR_MISSING"
ROADMAP_NOT_FOUND = "ROADMAP_NOT_FOUND"
ROADMAP_STATUS_INVALID = "ROADMAP_STATUS_INVALID"
PROJECTION_UNREADABLE = "PROJECTION_UNREADABLE"
RUNNER_INVALID = "RUNNER_INVALID"  # G08/PROV-01
RUNNER_UNKNOWN = "RUNNER_UNKNOWN"  # G08/PROV-02
SCHEMA_INVALID = "SCHEMA_INVALID"
SCHEMA_MISSING = "SCHEMA_MISSING"
SNAPSHOT_ARCHIVE_MISSING = "SNAPSHOT_ARCHIVE_MISSING"
SNAPSHOT_BEFORE_UNVERIFIED = "SNAPSHOT_BEFORE_UNVERIFIED"
SNAPSHOT_TAIL_MISSING = "SNAPSHOT_TAIL_MISSING"
STORE_LOCK_TIMEOUT = "STORE_LOCK_TIMEOUT"
APPEND_VERIFY_FAILED = "APPEND_VERIFY_FAILED"
LOCK_TAKEOVER = "LOCK_TAKEOVER"
TASK_NOT_FOUND = "TASK_NOT_FOUND"
UNKNOWN_ACTION = "UNKNOWN_ACTION"
UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
VERIFY_NOT_OK = "VERIFY_NOT_OK"
WRITE_CONFLICT = "WRITE_CONFLICT"
# Corrupted store sub-codes (raised via CorruptedStoreError):
JSONL_INVALID = "JSONL_INVALID"
EVENT_SEQ_INVALID = "EVENT_SEQ_INVALID"
EVENT_ID_DUPLICATE = "EVENT_ID_DUPLICATE"
EVENT_MISSING_FIELDS = "EVENT_MISSING_FIELDS"
CHAIN_BROKEN = "CHAIN_BROKEN"
CHAIN_ALREADY_ANCHORED = "CHAIN_ALREADY_ANCHORED"
CHAIN_NOT_ANCHORED = "CHAIN_NOT_ANCHORED"
# Stale-state codes do append_transactional (FIX-1806):
STALE_STATE_SEQ = "STALE_STATE_SEQ"
STALE_STATE_HASH = "STALE_STATE_HASH"

OPERATIONAL_CODES = frozenset(
    {
        ADAPTER_EXECUTE_FAILED,
        BOUNDARY_VIOLATION,
        EDIT_AMBIGUOUS,
        EDIT_BASE_MISMATCH,
        EDIT_INVALID,
        EDIT_TARGET_NOT_FOUND,
        EXTERNAL_ROOT_NOT_ALLOWED,
        FILE_UPDATE_DUPLICATE_PATH,
        RESOURCE_LIMIT_EXCEEDED,
        BOOTSTRAP_PROFILE_INVALID,
        BOOTSTRAP_TARGET_EXISTS,
        CLEAR_REQUIRES_FORCE,
        DUPLICATE_TASK,
        EVENT_SEQ_NON_MONOTONIC,
        INIT_BLOCKED,
        INPUT_INVALID,
        INPUT_NOT_FOUND,
        INVALID_ARGUMENT,
        ISSUE_NOT_FOUND,
        MAX_ATTEMPTS_EXCEEDED,
        PLUGIN_FORBIDDEN_FILE,
        PLUGIN_INPUT_INVALID,
        PLUGIN_INVALID_ID,
        PLUGIN_INVALID_JSON,
        PLUGIN_LOCK_INVALID,
        PLUGIN_NOT_A_DIRECTORY,
        PLUGIN_NOT_FOUND,
        PLUGIN_NOT_INSTALLED,
        PLUGIN_PATH_INVALID,
        PLUGIN_ROADMAP_INVALID,
        PLUGIN_SCHEMA_INVALID,
        PLUGIN_TARGET_EXISTS,
        PROJECTION_UNREADABLE,
        RUNNER_INVALID,
        RUNNER_UNKNOWN,
        ROADMAP_DIR_MISSING,
        ROADMAP_LOCK_INVALID,
        ROADMAP_NOT_FOUND,
        ROADMAP_STATUS_INVALID,
        SCHEMA_INVALID,
        SCHEMA_MISSING,
        SNAPSHOT_ARCHIVE_MISSING,
        SNAPSHOT_BEFORE_UNVERIFIED,
        SNAPSHOT_TAIL_MISSING,
        STORE_LOCK_TIMEOUT,
        APPEND_VERIFY_FAILED,
        LOCK_TAKEOVER,
        TASK_NOT_FOUND,
        UNKNOWN_ACTION,
        UNKNOWN_COMMAND,
        VERIFY_NOT_OK,
        WRITE_CONFLICT,
        JSONL_INVALID,
        EVENT_SEQ_INVALID,
        EVENT_ID_DUPLICATE,
        EVENT_MISSING_FIELDS,
        CHAIN_BROKEN,
        CHAIN_ALREADY_ANCHORED,
        CHAIN_NOT_ANCHORED,
        STALE_STATE_SEQ,
        STALE_STATE_HASH,
    }
)


# =============================================================================
# Hotfix (FIX-1811) — validate_hotfix_request / build_hotfix_event.
# =============================================================================
HOTFIX_INVALID = "HOTFIX_INVALID"
HOTFIX_ALREADY_EXISTS = "HOTFIX_ALREADY_EXISTS"
HOTFIX_ISSUE_NOT_FOUND = "HOTFIX_ISSUE_NOT_FOUND"
HOTFIX_ISSUE_NOT_OPEN = "HOTFIX_ISSUE_NOT_OPEN"
HOTFIX_TARGET_NOT_FOUND = "HOTFIX_TARGET_NOT_FOUND"
HOTFIX_TARGET_NOT_DONE = "HOTFIX_TARGET_NOT_DONE"
HOTFIX_SCOPE_INVALID = "HOTFIX_SCOPE_INVALID"

HOTFIX_CODES = frozenset(
    {
        HOTFIX_INVALID,
        HOTFIX_ALREADY_EXISTS,
        HOTFIX_ISSUE_NOT_FOUND,
        HOTFIX_ISSUE_NOT_OPEN,
        HOTFIX_TARGET_NOT_FOUND,
        HOTFIX_TARGET_NOT_DONE,
        HOTFIX_SCOPE_INVALID,
    }
)


# =============================================================================
# Conjunto canonico completo.
# =============================================================================
ALL_CODES: frozenset[str] = WORKFLOW_GATE_CODES | OPERATIONAL_CODES | HOTFIX_CODES


__all__ = [
    # workflow gate codes
    "MISSING_CLAIM",
    "MISSING_COMPLETE",
    "MISSING_VERIFICATION",
    "WORKFLOW_GATE_VIOLATION",
    "ACTION_COLLAPSE",
    "PRIOR_STATUS_MISMATCH",
    "LOCK_VIOLATION",
    "IMMUTABLE_DONE_VIOLATION",
    "REVIEW_ROLE_VIOLATION",
    # operational codes
    "ADAPTER_EXECUTE_FAILED",
    "BOUNDARY_VIOLATION",
    "EDIT_AMBIGUOUS",
    "EDIT_BASE_MISMATCH",
    "EDIT_INVALID",
    "EDIT_TARGET_NOT_FOUND",
    "EXTERNAL_ROOT_NOT_ALLOWED",
    "FILE_UPDATE_DUPLICATE_PATH",
    "RESOURCE_LIMIT_EXCEEDED",
    "CLEAR_REQUIRES_FORCE",
    "BOOTSTRAP_PROFILE_INVALID",
    "BOOTSTRAP_TARGET_EXISTS",
    "DUPLICATE_TASK",
    "EVENT_SEQ_NON_MONOTONIC",
    "INIT_BLOCKED",
    "INPUT_INVALID",
    "INPUT_NOT_FOUND",
    "INVALID_ARGUMENT",
    "ISSUE_NOT_FOUND",
    "MAX_ATTEMPTS_EXCEEDED",
    "PLUGIN_FORBIDDEN_FILE",
    "PLUGIN_INPUT_INVALID",
    "PLUGIN_INVALID_ID",
    "PLUGIN_INVALID_JSON",
    "PLUGIN_LOCK_INVALID",
    "PLUGIN_NOT_A_DIRECTORY",
    "PLUGIN_NOT_FOUND",
    "PLUGIN_NOT_INSTALLED",
    "PLUGIN_PATH_INVALID",
    "PLUGIN_ROADMAP_INVALID",
    "PLUGIN_SCHEMA_INVALID",
    "PLUGIN_TARGET_EXISTS",
    "PROJECTION_UNREADABLE",
    "RUNNER_INVALID",
    "RUNNER_UNKNOWN",
    "ROADMAP_DIR_MISSING",
    "ROADMAP_LOCK_INVALID",
    "ROADMAP_NOT_FOUND",
    "ROADMAP_STATUS_INVALID",
    "SCHEMA_INVALID",
    "SCHEMA_MISSING",
    "SNAPSHOT_ARCHIVE_MISSING",
    "SNAPSHOT_BEFORE_UNVERIFIED",
    "SNAPSHOT_TAIL_MISSING",
    "STORE_LOCK_TIMEOUT",
    "APPEND_VERIFY_FAILED",
    "LOCK_TAKEOVER",
    "TASK_NOT_FOUND",
    "UNKNOWN_ACTION",
    "UNKNOWN_COMMAND",
    "VERIFY_NOT_OK",
    "WRITE_CONFLICT",
    "JSONL_INVALID",
    "EVENT_SEQ_INVALID",
    "EVENT_ID_DUPLICATE",
    "EVENT_MISSING_FIELDS",
    "CHAIN_BROKEN",
    "CHAIN_ALREADY_ANCHORED",
    "CHAIN_NOT_ANCHORED",
    "STALE_STATE_SEQ",
    "STALE_STATE_HASH",
    # hotfix codes
    "HOTFIX_INVALID",
    "HOTFIX_ALREADY_EXISTS",
    "HOTFIX_ISSUE_NOT_FOUND",
    "HOTFIX_ISSUE_NOT_OPEN",
    "HOTFIX_TARGET_NOT_FOUND",
    "HOTFIX_TARGET_NOT_DONE",
    "HOTFIX_SCOPE_INVALID",
    # sets
    "WORKFLOW_GATE_CODES",
    "OPERATIONAL_CODES",
    "HOTFIX_CODES",
    "ALL_CODES",
]
